const API_BASE = ''; // Set to 'http://localhost:8081/api' after starting the backend.
const demoItems=[
 {id:1,title:'Black JBL Earbuds Case',category:'Electronics',location:'Hostel A common room',date:'2026-08-29T18:30',type:'FOUND',status:'OPEN',description:'A black charging case found near the sofa. Tell us the earbuds model to verify.',emoji:'🎧'},
 {id:2,title:'Blue Water Bottle',category:'Accessories',location:'Library, 2nd floor',date:'2026-08-30T10:15',type:'LOST',status:'OPEN',description:'Blue steel bottle with a small campus sticker.',emoji:'🧴'},
 {id:3,title:'Calculus Textbook',category:'Books',location:'Study room 3',date:'2026-08-29T21:00',type:'FOUND',status:'OPEN',description:'Engineering mathematics book. Share a note or marking inside to verify ownership.',emoji:'📚'},
 {id:4,title:'Set of Keys',category:'Keys',location:'Mess entrance',date:'2026-08-28T13:30',type:'FOUND',status:'OPEN',description:'A keyring was deposited at the hostel office. Describe the keychain to claim it.',emoji:'🔑'},
 {id:5,title:'Student ID Card',category:'ID Cards',location:'Basketball court',date:'2026-08-27T16:00',type:'FOUND',status:'OPEN',description:'ID card held safely by the admin. Verify your name and roll number privately.',emoji:'🪪'},
 {id:6,title:'Grey Hoodie',category:'Clothes',location:'Laundry room',date:'2026-08-26T19:10',type:'LOST',status:'OPEN',description:'Grey hoodie, size M.',emoji:'👕'}];
const sensitive=['Wallet','ID Cards','Electronics','Keys'];
function getItems(){return JSON.parse(localStorage.getItem('hf-items')||'null')||demoItems}
function saveItems(items){localStorage.setItem('hf-items',JSON.stringify(items))}
function icon(item){return item.emoji||({Electronics:'🎧','ID Cards':'🪪',Keys:'🔑',Clothes:'👕',Books:'📚',Wallet:'👛',Accessories:'🎒',Other:'📦'}[item.category]||'📦')}
function formatDate(value){return new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}
function card(item){return `<a class="card" href="detail.html?id=${item.id}"><div class="card-image">${icon(item)}</div><div class="card-body"><div class="badges"><span class="badge ${item.type==='LOST'?'lost':''}">${item.type}</span><span class="muted">${item.category}</span></div><h3>${item.title}</h3><p>📍 ${item.location}</p><p>📅 ${formatDate(item.date)}</p></div></a>`}
function renderItems(items,target){document.querySelector(target).innerHTML=items.map(card).join('')||'<p class="muted">No matching items found.</p>'}
function query(){return new URLSearchParams(location.search)}
function initNav(){document.querySelectorAll('.menu').forEach(b=>b.onclick=()=>document.querySelector('nav')?.classList.toggle('show'))}
function initHome(){const el=document.querySelector('#recent-items');if(!el)return;renderItems(getItems().filter(i=>i.status==='OPEN').slice(0,3),'#recent-items');document.querySelector('#home-search').onsubmit=e=>{e.preventDefault();location.href='items.html?q='+encodeURIComponent(new FormData(e.target).get('q'))}}
function initBrowse(){const list=document.querySelector('#item-list');if(!list)return;const q=query().get('q')||'';document.querySelector('#search').value=q;const update=()=>{const term=document.querySelector('#search').value.toLowerCase(),cat=document.querySelector('#category').value,type=document.querySelector('#type').value;const filtered=getItems().filter(i=>i.status==='OPEN'&&(!term||`${i.title} ${i.description} ${i.location}`.toLowerCase().includes(term))&&(!cat||i.category===cat)&&(!type||i.type===type));document.querySelector('#result-count').textContent=`${filtered.length} item${filtered.length!==1?'s':''} found`;renderItems(filtered,'#item-list')};document.querySelectorAll('#search,#category,#type').forEach(x=>x.addEventListener('input',update));update()}
function initReport(){const form=document.querySelector('#report-form');if(!form)return;const type=query().get('type')==='FOUND'?'FOUND':'LOST';document.querySelector('#report-title').textContent=`Report ${type==='FOUND'?'a found':'a lost'} item`;form.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form));const item={...d,id:Date.now(),type,status:'PENDING',date:d.date||new Date().toISOString(),emoji:icon(d)};saveItems([item,...getItems()]);form.innerHTML='<h2>Report submitted</h2><p class="muted">Thank you. An admin will review it before it is published.</p><a class="btn primary" href="index.html">Back to home</a>'}}
function initDetail(){const root=document.querySelector('#detail');if(!root)return;const item=getItems().find(i=>String(i.id)===query().get('id'));if(!item){root.innerHTML='<h1>Item not found</h1>';return}root.innerHTML=`<div class="detail-image">${icon(item)}</div><div><div class="badges"><span class="badge ${item.type==='LOST'?'lost':''}">${item.type}</span><span class="badge">${item.status}</span></div><h1>${item.title}</h1><p class="muted">${item.category} · ${formatDate(item.date)}</p><p>📍 <strong>${item.location}</strong></p><p>${item.description}</p>${item.status==='OPEN'?`<button class="btn primary" id="claim">Claim this item</button><form class="form-card claim-box" id="claim-form" hidden><label>Proof of ownership<textarea required placeholder="Describe a detail that is not public, such as a marking, contents, or serial detail."></textarea></label><button class="btn primary">Submit claim</button></form>`:'<p class="muted">This item is no longer open for claims.</p>'}</div>`;document.querySelector('#claim')?.addEventListener('click',()=>document.querySelector('#claim-form').hidden=false);document.querySelector('#claim-form')?.addEventListener('submit',e=>{e.preventDefault();alert('Claim submitted. The hostel admin will verify your details privately.');e.target.reset()})}
function initAdmin(){const root=document.querySelector('#admin-items');if(!root)return;const render=()=>{const items=getItems();root.innerHTML=items.map(i=>`<article class="admin-row"><div><div class="badges"><span class="badge ${i.type==='LOST'?'lost':''}">${i.type}</span><span class="badge">${i.status}</span></div><h3>${i.title}</h3><p class="muted">${i.category} · ${i.location}</p></div><div class="admin-actions">${i.status==='PENDING'?'<button class="btn secondary" data-action="OPEN" data-id="'+i.id+'">Approve</button><button class="btn danger" data-action="REJECTED" data-id="'+i.id+'">Reject</button>':i.status==='OPEN'?'<button class="btn secondary" data-action="CLAIMED" data-id="'+i.id+'">Mark claimed</button>':i.status==='CLAIMED'?'<button class="btn primary" data-action="RETURNED" data-id="'+i.id+'">Mark returned</button>':'<span class="muted">Closed</span>'}</div></article>`).join('')};root.onclick=e=>{const b=e.target.closest('[data-id]');if(!b)return;const items=getItems();const i=items.find(x=>String(x.id)===b.dataset.id);i.status=b.dataset.action;saveItems(items);render()};render()}
function initMyReports(){if(document.querySelector('#my-items'))renderItems(getItems().filter(i=>i.status==='PENDING'),'#my-items')}
function initLogin(){document.querySelector('#login-form')?.addEventListener('submit',e=>{e.preventDefault();alert('Login will be connected after Spring Security is added in Phase 4.')})}
initNav();initHome();initBrowse();initReport();initDetail();initAdmin();initMyReports();initLogin();
